# Generated by Django 5.1.5 on 2025-01-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_alter_student_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="clas_date",
            field=models.DateTimeField(),
        ),
    ]
