# Generated by Django 5.1.5 on 2025-01-17 00:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0002_rename_datre_joined_teacher_date_joined"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="date_joined",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
