# Generated by Django 5.1.5 on 2025-01-17 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0003_alter_teacher_date_joined"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teacher",
            old_name="desccription",
            new_name="description",
        ),
    ]
