# Generated by Django 5.1.5 on 2025-01-18 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0008_alter_teacher_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="profile_image",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
