# Generated by Django 5.1.5 on 2025-01-18 07:02

import teachers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0009_teacher_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="profile_image",
            field=models.ImageField(
                null=True, upload_to=teachers.models.get_unique_filename
            ),
        ),
    ]
